task2/expenses/urls.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import path, reverse_lazy
from .models import Expense, Category
from .views import ExpenseListView, CategoryListView, CategoryUpdateView


urlpatterns = [
    path('expense/list/',
         ExpenseListView.as_view(),
         name='expense-list'),
    path('expense/create/',
         CreateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-create'),
    path('expense/<int:pk>/edit/',
         UpdateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-edit'),
    path('expense/<int:pk>/delete/',
         DeleteView.as_view(
            model=Expense,
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_delete.html'
         ),
         name='expense-delete'),

    path('category/list/',
         CategoryListView.as_view(),
         name='category-list'),
    path('category/create/',
         CreateView.as_view(
            model=Category,
            fields='__all__',
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_update.html'
         ),
         name='category-create'),
    path('category/<int:pk>/delete/',
         DeleteView.as_view(
            model=Category,
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_delete.html'
         ),
         name='category-delete'),
    path('category/<int:pk>/update/',
         CategoryUpdateView.as_view(
            model=Category,
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_update.html'
         ),
         name='category-update'),
]

task2/project/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='expenses:expense-list'),
         name='dashboard'),
    path('expenses/',
         include(('expenses.urls', 'expenses'), namespace='expenses')),
]

task2/expenses/models.py
import datetime
from django.db import models


class Category(models.Model):
    class Meta:
        ordering = ('name',)

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'


class Expense(models.Model):
    class Meta:
        ordering = ('-date', '-pk')

    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True)

    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    date = models.DateField(default=datetime.date.today, db_index=True)

    def __str__(self):
        return f'{self.date} {self.name} {self.amount}'

task2/expenses/forms.py
from django import forms
from .models import Expense, Category


class ExpenseSearchForm(forms.ModelForm):
    date_from = forms.DateField(
        required=False,
        input_formats=['%d.%m.%Y'],
        widget=forms.DateInput(attrs={'placeholder': 'dd.mm.yyyy'})
    )
    date_to = forms.DateField(
        required=False,
        input_formats=['%d.%m.%Y'],
        widget=forms.DateInput(attrs={'placeholder': 'dd.mm.yyyy'})
    )
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-check-input'})
    )
    SORT_CHOICES = (
        ('date', 'Date'),
        ('category', 'Category')
    )
    SORT_ORDER_CHOICES = (
        ('asc', 'Ascending'),
        ('desc', 'Descending')
    )
    sort_by = forms.ChoiceField(
        choices=SORT_CHOICES,
        required=False,
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    sort_order = forms.ChoiceField(
        choices=SORT_ORDER_CHOICES,
        required=False,
        widget=forms.Select(attrs={'class': 'form-select'})
    )

    class Meta:
        model = Expense
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False

task2/expenses/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from django.db.models import Count, Sum

from .forms import ExpenseSearchForm
from .models import Expense, Category
from .reports import summary_per_category, total_per_year, total_per_month


class ExpenseListView(ListView):
    model = Expense
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list
        total_amount = 0

        form = ExpenseSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data.get('name', '').strip()
            date_from = form.cleaned_data.get('date_from', None)
            date_to = form.cleaned_data.get('date_to', None)
            categories = form.cleaned_data.get('categories', None)
            sort_by = form.cleaned_data.get('sort_by', None)
            sort_order = form.cleaned_data.get('sort_order', 'asc')

            if name:
                queryset = queryset.filter(name__icontains=name)
            if date_from:
                queryset = queryset.filter(date__gte=date_from)
            if date_to:
                queryset = queryset.filter(date__lte=date_to)
            if categories:
                queryset = queryset.filter(category__in=categories)
            if sort_by:
                if sort_order == 'desc':
                    sort_by = '-' + sort_by
                queryset = queryset.order_by(sort_by)

            total_amount = queryset.aggregate(Sum('amount'))['amount__sum'] or 0

        return super().get_context_data(
            form=form,
            object_list=queryset,
            total_amount=total_amount,
            summary_per_category=summary_per_category(queryset),
            total_per_year=total_per_year(queryset),
            total_per_month=total_per_month(queryset),
            **kwargs)


class CategoryListView(ListView):
    model = Category
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.annotate(expense_count=Count('expense'))
        return queryset


class CategoryUpdateView(UpdateView):
    model = Category
    fields = ['name']

task2/expenses/templates/expenses/category_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'expenses:category-create' %}">add</a>

<table border="1">
	<thead>
		<tr>
			<th>name</th>
			<th>expenses count</th>
			<th>actions</th>
		</tr>
	</thead>
	<tbody>
		{% for obj in object_list %}
		<tr>
			<td>
				{{obj.name}}
			</td>
			<td>
				{{ obj.expense_count }}
			</td>
			<td>
				<a href="{% url 'expenses:category-update' obj.id %}">edit</a>
				<a href="{% url 'expenses:category-delete' obj.id %}">delete</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

task2/expenses/templates/expenses/expense_list.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'expenses:expense-create' %}">add</a>

<form method="get" action="">
  {{form.as_p}}
  <button type="submit">search</button>
</form>
<br>
<table border="1">
	<caption>Expenses</caption>
	<thead>
	  <tr>
		<th>no.</th>
		<th>category</th>
		<th>name</th>
		<th>amount</th>
		<th>date</th>
		<th>actions</th>
	  </tr>
	</thead>
	<tbody>

	{% for obj in object_list %}
	  <tr>
		<td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
		<td>{{ obj.category|default:"-" }}</td>
		<td>{{ obj.name|default:"-" }}</td>
		<td>{{ obj.amount|floatformat:2 }}</td>
		<td>{{obj.date}}</td>
		<td>
		  <a href="{% url 'expenses:expense-edit' obj.id %}">edit</a>
		  <a href="{% url 'expenses:expense-delete' obj.id %}">delete</a>
		</td>
	  </tr>
	  {% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>

{% include "_pagination.html" %}
<hr>
<style>
  .table-container {
    display: table-row;
  }
  table {
    display: table-cell;
    padding: 10px;
  }
  caption {
    margin-bottom: 10px;
  }
  span {
    margin-right: 10px;
  }
</style>

<div class="table-container">
  <table border="1">
    <caption>Total expenses per year</caption>
    <thead>
      <tr>
        <th>Year</th>
        <th>Total Amount</th>
      </tr>
    </thead>
    <tbody>
      {% for total in total_per_year %}
        <tr>
          <td>{{ total.year }}</td>
          <td>{{ total.total|floatformat:2 }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <table border="1">
    <caption>Total expenses per month</caption>
    <thead>
      <tr>
        <th>Month</th>
        <th>Total Amount</th>
      </tr>
    </thead>
    <tbody>
      {% for total in total_per_month %}
        <tr>
          <td>{{ total.year }}.{{ total.month }}</td>
          <td>{{ total.total|floatformat:2 }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <table border="1">
    <caption>Total expenses per category</caption>
    <thead>
      <tr>
        <th>Category</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      {% for category, total in summary_per_category.items %}
        <tr>
          <td>{{ category }}</td>
          <td>{{ total|floatformat:2 }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <table border="1">
    <caption>Total amount spent</caption>
    <thead>
      <tr>
        <th>Total Amount</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ total_amount|floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

task2/project/templates/_pagination.html
<div class="pagination">
    <span class="pagination__nav">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
<!--
  Problem: losing form state after click pagination link
  Solve: prevent default action and include form data in url then use window.location.href
-->
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var form = document.querySelector('form');
    var paginationLinks = document.querySelectorAll('.pagination a');

    paginationLinks.forEach(function(link) {
      link.addEventListener('click', function(event) {
        event.preventDefault();

        var formValues = new URLSearchParams(new FormData(form)).toString();
        var url = link.getAttribute('href');

        if (url.includes('?')) {
          url += '&' + formValues;
        } else {
          url += '?' + formValues;
        }
        window.location.href = url;
      });
    });
  });
</script>

task2/project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block meta_title %}Expenses app{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
	<a href="{% url 'expenses:expense-list' %}">Expenses</a> | 
	<a href="{% url 'expenses:category-list' %}">Categories</a> | 
	<hr>
    {% block content %}{% endblock %}
  </body>
</html>

task2/project/templates/generic_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">delete</button>
</form>

{% endblock %}

task2/project/templates/generic_update.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">save</button>
</form>

{% endblock %}